data(['masculino', '0-17', 'saudavel', 'tempo_pouco', 'preco_baixo', 'carnes', 'classificacao_boa', 'no']).
data(['masculino', '18-40', 'saudavel', 'tempo_pouco', 'preco_medio', 'portuguesa', 'classificacao_media', 'no']).
data(['masculino', '41-100', 'saudavel', 'tempo_pouco', 'preco_alto', 'churrasco', 'classificacao_baixo', 'no']).
data(['masculino', '0-17', 'nao_saudavel', 'tempo_medio', 'preco_baixo', 'hamburguer', 'classificacao_boa', 'yes']).
data(['masculino', '18-40', 'nao_saudavel', 'tempo_baixo', 'preco_baixo', 'fast_food', 'classificacao_media', 'yes']).
data(['masculino', '41-100', 'nao_saudavel', 'tempo_medio', 'preco_medio', 'vegetariana', 'classificacao_baixo', 'no']).
data(['masculino', '0-17', 'saudavel', 'tempo_alto', 'preco_medio', 'italiana', 'classificacao_media', 'yes']).
data(['masculino', '18-40', 'saudavel', 'tempo_alto', 'preco_alto', 'massa', 'classificacao_media', 'yes']).
data(['masculino', '41-100', 'saudavel', 'tempo_alto', 'preco_alto', 'marisco', 'classificacao_boa', 'yes']).
data(['masculino', '0-17', 'nao_saudavel', 'tempo_pouco', 'preco_baixo', 'japonesa', 'classificacao_boa', 'no']).
data(['masculino', '18-40', 'nao_saudavel', 'tempo_pouco', 'preco_baixo', 'peixe', 'classificacao_media', 'no']).
data(['masculino', '41-100', 'nao_saudavel', 'tempo_pouco', 'preco_baixo', 'sushi', 'classificacao_baixo', 'no']).
data(['masculino', '0-17', 'saudavel', 'tempo_baixo', 'preco_baixo', 'sobremesa', 'classificacao_boa', 'no']).
data(['masculino', '18-40', 'saudavel', 'tempo_medio', 'preco_medio', 'pizza', 'classificacao_media', 'no']).
data(['masculino', '41-100', 'saudavel', 'tempo_baixo', 'preco_baixo', 'salada', 'classificacao_media', 'yes']).
data(['masculino', '0-17', 'nao_saudavel', 'tempo_alto', 'preco_alto', 'carnes', 'classificacao_boa', 'yes']).
data(['masculino', '18-40', 'nao_saudavel', 'tempo_alto', 'preco_alto', 'portuguesa', 'classificacao_boa', 'yes']).
data(['masculino', '41-100', 'nao_saudavel', 'tempo_medio', 'preco_baixo', 'churrasco', 'classificacao_media', 'yes']).
data(['masculino', '0-17', 'saudavel', 'tempo_pouco', 'preco_alto', 'hamburguer', 'classificacao_media', 'no']).
data(['masculino', '18-40', 'saudavel', 'tempo_medio', 'preco_baixo', 'fast_food', 'classificacao_media', 'no']).
data(['masculino', '41-100', 'saudavel', 'tempo_alto', 'preco_medio', 'vegetariana', 'classificacao_baixo', 'yes']).
data(['feminino', '0-17', 'nao_saudavel', 'tempo_medio', 'preco_alto', 'italiana', 'classificacao_boa', 'no']).
data(['feminino', '18-40', 'nao_saudavel', 'tempo_pouco', 'preco_baixo', 'massa', 'classificacao_media', 'no']).
data(['feminino', '41-100', 'nao_saudavel', 'tempo_alto', 'preco_alto', 'marisco', 'classificacao_boa', 'no']).
data(['feminino', '0-17', 'saudavel', 'tempo_medio', 'preco_alto', 'japonesa', 'classificacao_boa', 'yes']).
data(['feminino', '18-40', 'saudavel', 'tempo_alto', 'preco_medio', 'peixe', 'classificacao_boa', 'yes']).
data(['feminino', '41-100', 'saudavel', 'tempo_medio', 'preco_alto', 'sushi', 'classificacao_boa', 'yes']).
data(['feminino', '0-17', 'nao_saudavel', 'tempo_baixo', 'preco_medio', 'sobremesa', 'classificacao_boa', 'yes']).
data(['feminino', '18-40', 'nao_saudavel', 'tempo_medio', 'preco_medio', 'pizza', 'classificacao_media', 'yes']).
data(['feminino', '41-100', 'nao_saudavel', 'tempo_alto', 'preco_baixo', 'salada', 'classificacao_baixo', 'no']).
data(['feminino', '0-17', 'saudavel', 'tempo_pouco', 'preco_baixo', 'carnes', 'classificacao_boa', 'no']).
data(['feminino', '18-40', 'saudavel', 'tempo_medio', 'preco_medio', 'portuguesa', 'classificacao_media', 'no']).
data(['feminino', '41-100', 'saudavel', 'tempo_pouco', 'preco_medio', 'churrasco', 'classificacao_media', 'no']).
data(['feminino', '0-17', 'nao_saudavel', 'tempo_medio', 'preco_baixo', 'hamburguer', 'classificacao_boa', 'yes']).
data(['feminino', '18-40', 'nao_saudavel', 'tempo_baixo', 'preco_baixo', 'fast_food', 'classificacao_media', 'yes']).
data(['feminino', '41-100', 'nao_saudavel', 'tempo_medio', 'preco_alto', 'vegetariana', 'classificacao_baixo', 'no']).
data(['feminino', '0-17', 'saudavel', 'tempo_medio', 'preco_baixo', 'italiana', 'classificacao_boa', 'yes']).
data(['feminino', '18-40', 'saudavel', 'tempo_alto', 'preco_alto', 'massa', 'classificacao_media', 'yes']).
data(['feminino', '41-100', 'saudavel', 'tempo_alto', 'preco_medio', 'marisco', 'classificacao_baixo', 'yes']).
data(['feminino', '0-17', 'nao_saudavel', 'tempo_pouco', 'preco_medio', 'japonesa', 'classificacao_boa', 'no']).
data(['feminino', '18-40', 'nao_saudavel', 'tempo_medio', 'preco_alto', 'peixe', 'classificacao_media', 'no']).
data(['feminino', '41-100', 'nao_saudavel', 'tempo_alto', 'preco_alto', 'sushi', 'classificacao_baixo', 'no']).
